force_cast: warning # implicitly
disabled_rules:
  - identifier_name
  - private_over_fileprivate
  - cyclomatic_complexity
  - trailing_whitespace
excluded:
- Carthage
- Pods
line_length:
- 300
- 400
file_length:
- 1000
- 2000
type_body_length:
- 500
type_name:
  min_length:
   warning: 1
   error: 0
  max_length: 
    warning: 50
    error: 60
